#version: '2.1'
version: '3'
services:
    python:
        container_name: python-lab
        hostname: python-lab
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./apps:/apps:rw
#            - ./docs:/docs:rw
#        ports:
#            - 8000:8000
